<?php

namespace app\common\controllers;

use app\models\Users;
use yii\web\Controller;

class AdminController extends Controller
{
    public function beforeAction($action)
    {
        if (\Yii::$app->user->isGuest || Users::findOne(\Yii::$app->user->getId())->isAdmin == Users::IS_USER) {
            throw new \yii\web\NotFoundHttpException();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}