<?php

namespace app\common\controllers;
use app\models\Users;

class AuthController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if (\Yii::$app->user->isGuest || Users::findOne(\Yii::$app->user->getId())->isAdmin == Users::IS_ADMIN) {
            throw new \yii\web\NotFoundHttpException();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}