<?php

namespace app\common\controllers;

use yii\web\Controller;

class AuthAjaxController extends Controller
{
    public function beforeAction($action)
    {
        if (\Yii::$app->user->isGuest) {
            throw new \yii\web\NotFoundHttpException();
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function renderJson(bool $state, $data = null, string $message = null)
    {
        return json_encode([
            'status'  => $state,
            'message' => $message,
            'data'    => $data,
        ]);
    }
}